"""
Django settings for secretaria_it project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de ambiente do arquivo .env na raiz do projeto (se existir)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s7!u+b(y*a5xx$@el2st*+k_wc^f+$3ukhqoc3o%fzlq*@qxw3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'secretaria_it',
    'funcionarios',
    'pacientes',
    'veiculos',
    'viagens',
    'tfd',
    'regulacao',
    'rh',
    'motorista',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'secretaria_it.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['secretaria_it/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'secretaria_it.context_processors.group_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'secretaria_it.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



_SMS_DB_NAME = os.getenv('SMS_DB_NAME') or os.getenv('ESUS_DB_NAME') or 'smsiturama'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _SMS_DB_NAME,
        'USER': os.getenv('SMS_DB_USER') or os.getenv('ESUS_DB_USER', 'postgres'),
        'PASSWORD': os.getenv('SMS_DB_PASSWORD') or os.getenv('ESUS_DB_PASSWORD', ''),
        'HOST': os.getenv('SMS_DB_HOST') or os.getenv('ESUS_DB_HOST', 'localhost'),
        'PORT': os.getenv('SMS_DB_PORT') or os.getenv('ESUS_DB_PORT', '5432'),  
    },
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Origem padrão para viagens de motoristas (pode ser sobrescrito por variável de ambiente)
DEFAULT_ORIGEM = os.getenv('DEFAULT_ORIGEM', 'Iturama')

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Configurações de sessão para login único
SESSION_COOKIE_AGE = 86400  # 24 horas (1 dia)
SESSION_SAVE_EVERY_REQUEST = True  # Renova sessão a cada request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Não expira ao fechar browser
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Mude para True se usar HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'

# Mantemos o CsrfViewMiddleware ativo também em desenvolvimento para garantir
# logout/login e demais POSTs com proteção adequada. Use o helper JS para fetch
# (já incluído em base.html) que injeta o cabeçalho X-CSRFToken automaticamente.

