# Generated by Django 5.2.5 on 2025-09-18 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_alter_paciente_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Médico')),
                ('crm', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('especialidade', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médico Solicitante',
                'verbose_name_plural': 'Médicos Solicitantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Exame')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('codigo_sus', models.CharField(blank=True, max_length=20, verbose_name='Código SUS')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Exame',
                'verbose_name_plural': 'Tipos de Exames',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da UBS')),
                ('endereco', models.TextField(blank=True, max_length=300, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('responsavel', models.CharField(blank=True, max_length=150, verbose_name='Responsável')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UBS',
                'verbose_name_plural': 'UBS',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegulacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(help_text='Motivo/indicação clínica para o exame', verbose_name='Justificativa Clínica')),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('emergencia', 'Emergência')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('observacoes_solicitacao', models.TextField(blank=True, verbose_name='Observações da Solicitação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('negado', 'Negado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_regulacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Regulação')),
                ('motivo_decisao', models.TextField(blank=True, help_text='Motivo da autorização ou negação', verbose_name='Motivo da Decisão')),
                ('local_realizacao', models.CharField(blank=True, max_length=200, verbose_name='Local de Realização')),
                ('data_agendada', models.DateField(blank=True, null=True, verbose_name='Data Agendada')),
                ('observacoes_regulacao', models.TextField(blank=True, verbose_name='Observações da Regulação')),
                ('numero_protocolo', models.CharField(blank=True, help_text='Gerado automaticamente', max_length=50, unique=True, verbose_name='Número do Protocolo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulacao.medicosolicitante', verbose_name='Médico Solicitante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente', verbose_name='Paciente')),
                ('regulador', models.ForeignKey(blank=True, help_text='Usuário que fez a regulação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Regulador')),
                ('tipo_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulacao.tipoexame', verbose_name='Tipo de Exame')),
                ('ubs_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulacao.ubs', verbose_name='UBS Solicitante')),
            ],
            options={
                'verbose_name': 'Regulação de Exame',
                'verbose_name_plural': 'Regulações de Exames',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.AddField(
            model_name='medicosolicitante',
            name='ubs_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulacao.ubs', verbose_name='UBS Padrão'),
        ),
    ]
