# Generated by Django 5.2.5 on 2025-09-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoexame',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='regulacaoexame',
            name='prioridade',
            field=models.CharField(choices=[('normal', 'Normal'), ('media', 'Média'), ('alta', 'Alta')], default='normal', max_length=20, verbose_name='Prioridade'),
        ),
    ]
