# Generated by Django 5.2.5 on 2025-09-21 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_cns_alter_paciente_nome'),
        ('regulacao', '0002_tipoexame_codigo_tipoexame_valor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da Especialidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='regulacaoexame',
            name='hora_agendada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Agendada'),
        ),
        migrations.AlterField(
            model_name='regulacaoexame',
            name='status',
            field=models.CharField(choices=[('fila', 'Fila de Espera'), ('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('negado', 'Negado'), ('cancelado', 'Cancelado')], default='fila', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='RegulacaoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(help_text='Motivo/indicação clínica para a consulta', verbose_name='Justificativa Clínica')),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('media', 'Média'), ('alta', 'Alta')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('observacoes_solicitacao', models.TextField(blank=True, verbose_name='Observações da Solicitação')),
                ('status', models.CharField(choices=[('fila', 'Fila de Espera'), ('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('negado', 'Negado'), ('cancelado', 'Cancelado')], default='fila', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_regulacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Regulação')),
                ('motivo_decisao', models.TextField(blank=True, help_text='Motivo da autorização ou negação', verbose_name='Motivo da Decisão')),
                ('local_atendimento', models.CharField(blank=True, max_length=200, verbose_name='Local de Atendimento')),
                ('data_agendada', models.DateField(blank=True, null=True, verbose_name='Data Agendada')),
                ('hora_agendada', models.TimeField(blank=True, null=True, verbose_name='Hora Agendada')),
                ('observacoes_regulacao', models.TextField(blank=True, verbose_name='Observações da Regulação')),
                ('numero_protocolo', models.CharField(blank=True, help_text='Gerado automaticamente', max_length=50, unique=True, verbose_name='Número do Protocolo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulacao.especialidade', verbose_name='Especialidade')),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulacao.medicosolicitante', verbose_name='Médico Solicitante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente', verbose_name='Paciente')),
                ('regulador', models.ForeignKey(blank=True, help_text='Usuário que fez a regulação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Regulador')),
                ('ubs_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulacao.ubs', verbose_name='UBS Solicitante')),
            ],
            options={
                'verbose_name': 'Regulação de Consulta',
                'verbose_name_plural': 'Regulações de Consultas',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
