# Generated by Django 5.2.5 on 2025-09-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0003_especialidade_regulacaoexame_hora_agendada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulacaoconsulta',
            name='medico_atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_consultas', to='regulacao.medicosolicitante', verbose_name='Médico Atendente'),
        ),
        migrations.AddField(
            model_name='regulacaoexame',
            name='medico_atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_exames', to='regulacao.medicosolicitante', verbose_name='Médico Atendente'),
        ),
    ]
