# Generated by Django 5.2.5 on 2025-09-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0003_regulacaoexame_numero_pedido'),
        ('regulacao', '0004_regulacaoconsulta_medico_atendente_and_more'),
    ]

    operations = [
    ]
