# Generated by Django 5.2.5 on 2025-09-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0003_resultado_atendimento_fields'),
        ('regulacao', '0008_resultado_atendimento_fields'),
    ]

    operations = [
    ]
