# Generated by Django 5.2.5 on 2025-09-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0003_pendencia_fields'),
        ('regulacao', '0009_merge_20250925_1937'),
    ]

    operations = [
    ]
