# Generated by Django 5.2.5 on 2025-09-27 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0012_merge_0003_notificacao_0011_pendencia_mensagens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='regulacao_n_user_id_5c62bf_idx',
            old_name='regulacao_n_user_l_a9e08f_idx',
        ),
        migrations.RenameIndex(
            model_name='pendenciamensagemconsulta',
            new_name='regulacao_p_consult_2dc978_idx',
            old_name='reg_cons_msg_idx',
        ),
        migrations.RenameIndex(
            model_name='pendenciamensagemexame',
            new_name='regulacao_p_exame_i_060983_idx',
            old_name='reg_exame_msg_idx',
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regulacaoconsulta',
            name='resultado_atendimento',
            field=models.CharField(choices=[('pendente', 'Aguardando'), ('compareceu', 'Compareceu'), ('faltou', 'Faltou')], db_index=True, default='pendente', max_length=12, verbose_name='Resultado do Atendimento'),
        ),
        migrations.AlterField(
            model_name='regulacaoexame',
            name='resultado_atendimento',
            field=models.CharField(choices=[('pendente', 'Aguardando'), ('compareceu', 'Compareceu'), ('faltou', 'Faltou')], db_index=True, default='pendente', max_length=12, verbose_name='Resultado do Atendimento'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioubs',
            unique_together={('user',)},
        ),
    ]
