# Generated by Django 5.2.5 on 2025-09-28 20:45

import django.db.models.deletion
from django.db import migrations, models


def copiar_medicos_para_ambulatorio(apps, schema_editor):
    RegulacaoConsulta = apps.get_model('regulacao', 'RegulacaoConsulta')
    MedicoSolicitante = apps.get_model('regulacao', 'MedicoSolicitante')
    MedicoAmbulatorio = apps.get_model('regulacao', 'MedicoAmbulatorio')
    Especialidade = apps.get_model('regulacao', 'Especialidade')
    # Para cada consulta com médico atendente antigo, criar (ou obter) um médico do ambulatório com mesmo CRM
    for rc in RegulacaoConsulta.objects.exclude(medico_atendente__isnull=True).all():
        try:
            old_med = MedicoSolicitante.objects.get(pk=rc.medico_atendente_id)
        except MedicoSolicitante.DoesNotExist:
            continue
        med_amb, _ = MedicoAmbulatorio.objects.get_or_create(
            crm=old_med.crm,
            defaults={'nome': old_med.nome, 'ativo': True},
        )
        # Vincular especialidade, se existir
        if rc.especialidade_id:
            try:
                espec = Especialidade.objects.get(pk=rc.especialidade_id)
                # Evita inserir duplicado na tabela M2M durante a migração
                through = med_amb.especialidades.through
                exists = through.objects.filter(
                    medicoambulatorio_id=med_amb.id,
                    especialidade_id=espec.id,
                ).exists()
                if not exists:
                    med_amb.especialidades.add(espec)
            except Especialidade.DoesNotExist:
                pass
        # Preencher campo novo
        setattr(rc, 'medico_atendente_new_id', med_amb.id)
        rc.save(update_fields=['medico_atendente_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0017_merge_0003_localatendimento_0016_alter_tipoexame_ativo_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoAmbulatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Médico')),
                ('crm', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('especialidades', models.ManyToManyField(blank=True, related_name='medicos_ambulatorio', to='regulacao.especialidade')),
            ],
            options={
                'verbose_name': 'Médico do Ambulatório',
                'verbose_name_plural': 'Médicos do Ambulatório',
                'ordering': ['nome'],
            },
        ),
        # Adiciona campo temporário para copiar dados
        migrations.AddField(
            model_name='regulacaoconsulta',
            name='medico_atendente_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='regulacao.medicoambulatorio', verbose_name='Médico Atendente'),
        ),
        migrations.RunPython(copiar_medicos_para_ambulatorio, migrations.RunPython.noop),
        # Remove campo antigo e renomeia o novo
        migrations.RemoveField(
            model_name='regulacaoconsulta',
            name='medico_atendente',
        ),
        migrations.RenameField(
            model_name='regulacaoconsulta',
            old_name='medico_atendente_new',
            new_name='medico_atendente',
        ),
    ]
