# Generated by Django 5.2.5 on 2025-09-28 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0018_medicoambulatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulacaoconsulta',
            name='medico_atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_consultas', to='regulacao.medicoambulatorio', verbose_name='Médico Atendente'),
        ),
        migrations.CreateModel(
            name='AgendaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('capacidade', models.PositiveIntegerField(default=10, help_text='Número máximo de pacientes a atender nesse dia', verbose_name='Capacidade por dia')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_medicas', to='regulacao.especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='regulacao.medicoambulatorio')),
            ],
            options={
                'verbose_name': 'Agenda Médica',
                'verbose_name_plural': 'Agendas Médicas',
                'ordering': ['medico__nome', 'especialidade__nome', 'dia_semana'],
                'indexes': [models.Index(fields=['medico', 'especialidade', 'dia_semana', 'ativo'], name='regulacao_a_medico__4c8ba8_idx')],
                'constraints': [models.UniqueConstraint(fields=('medico', 'especialidade', 'dia_semana'), name='uniq_agenda_medica_medico_especialidade_dia')],
            },
        ),
    ]
