# Generated by Django 5.2.5 on 2025-09-28 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0019_alter_regulacaoconsulta_medico_atendente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMedicaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('capacidade', models.PositiveIntegerField(default=10, verbose_name='Capacidade do dia')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_medicas_dia', to='regulacao.especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_dia', to='regulacao.medicoambulatorio')),
            ],
            options={
                'verbose_name': 'Agenda Médica (por dia)',
                'verbose_name_plural': 'Agendas Médicas (por dia)',
                'ordering': ['data', 'medico__nome'],
                'indexes': [models.Index(fields=['medico', 'especialidade', 'data', 'ativo'], name='regulacao_a_medico__320a37_idx')],
                'constraints': [models.UniqueConstraint(fields=('medico', 'especialidade', 'data'), name='uniq_agenda_medica_dia')],
            },
        ),
    ]
