# Generated by Django 5.2.5 on 2025-09-29 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0020_agendamedicadia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('autorizar_exame', 'Autorizar Exame'), ('negar_exame', 'Negar Exame'), ('pendenciar_exame', 'Pendenciar Exame'), ('autorizar_consulta', 'Autorizar Consulta'), ('negar_consulta', 'Negar Consulta'), ('pendenciar_consulta', 'Pendenciar Consulta')], max_length=30, verbose_name='Tipo de Ação')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('paciente_nome', models.CharField(max_length=200, verbose_name='Nome do Paciente')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo/Observação')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regulacao.regulacaoconsulta')),
                ('exame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regulacao.regulacaoexame')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_regulacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação do Usuário',
                'verbose_name_plural': 'Ações dos Usuários',
                'ordering': ['-data_acao'],
                'indexes': [models.Index(fields=['usuario', 'data_acao'], name='regulacao_a_usuario_47929a_idx'), models.Index(fields=['tipo_acao', 'data_acao'], name='regulacao_a_tipo_ac_a5e319_idx')],
            },
        ),
    ]
