# Generated by Django 5.2.5 on 2025-11-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0021_acaousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('codigo_cns', models.CharField(blank=True, max_length=15)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('cbo', models.CharField(blank=True, max_length=10)),
                ('cnes', models.CharField(blank=True, max_length=7)),
                ('ine', models.CharField(blank=True, max_length=15)),
                ('municipio', models.CharField(blank=True, max_length=150)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profissional MG',
                'verbose_name_plural': 'Profissionais MG',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['cpf'], name='regulacao_p_cpf_716e47_idx'), models.Index(fields=['codigo_cns'], name='regulacao_p_codigo__3c1463_idx'), models.Index(fields=['cnes'], name='regulacao_p_cnes_896180_idx')],
            },
        ),
    ]
