# Generated by Django 5.2.5 on 2025-11-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0022_profissionalmg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfissionalMG',
        ),
    ]
