# Generated by Django 5.2.5 on 2025-11-10 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulacao', '0023_delete_profissionalmg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoexame',
            name='especialidade',
            field=models.ForeignKey(blank=True, help_text='Utilizada para agenda e distribuição de vagas por profissional.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulacao.especialidade', verbose_name='Especialidade responsável'),
        ),
        migrations.RunSQL(
            sql="UPDATE regulacao_regulacaoexame SET medico_atendente_id = NULL WHERE medico_atendente_id IS NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='regulacaoexame',
            name='medico_atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_exames', to='regulacao.medicoambulatorio', verbose_name='Médico Atendente'),
        ),
    ]
