# Generated by Django 5.2.6 on 2025-09-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cargo', models.CharField(choices=[('medico', 'Medico'), ('administrativo', 'Administrativo'), ('motorista', 'Motorista')], max_length=20)),
                ('registro_profissional', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
