# Generated by Django 5.2.6 on 2025-09-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='registro_profissional',
        ),
    ]
