# Generated by Django 5.2.6 on 2025-09-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_remove_funcionario_registro_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('medico', 'Medico'), ('administrativo', 'Administrativo'), ('motorista', 'Motorista'), ('ti', 'Técnico de Informática')], max_length=20),
        ),
    ]
