# Generated by Django 5.2.5 on 2025-09-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cargo', models.CharField(max_length=100)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('vinculo', models.CharField(choices=[('concursado', 'Concursado'), ('seletista', 'Seletista'), ('comissionado', 'Comissionado')], default='concursado', max_length=15)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionário (RH)',
                'verbose_name_plural': 'Funcionários (RH)',
                'ordering': ['nome'],
            },
        ),
    ]
