# Generated by Django 5.2.5 on 2025-09-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_normalize_vinculo_celetista'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariorh',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='cep',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='doc_comprovante_endereco',
            field=models.FileField(blank=True, null=True, upload_to='rh/docs/comprovantes/'),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='doc_ctps',
            field=models.FileField(blank=True, null=True, upload_to='rh/docs/ctps/'),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='doc_rg',
            field=models.FileField(blank=True, null=True, upload_to='rh/docs/rg/'),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='setor_lotacao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='funcionariorh',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='funcionariorh',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='funcionariorh',
            name='vinculo',
            field=models.CharField(choices=[('concursado', 'Concursado'), ('celetista', 'Celetista'), ('comissionado', 'Comissionado')], default='concursado', max_length=15),
        ),
    ]
