# Generated by Django 5.2.5 on 2025-10-11 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_funcionariorh_bairro_funcionariorh_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtestadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data inicial')),
                ('data_fim', models.DateField(verbose_name='Data final')),
                ('dias', models.PositiveIntegerField(default=1, verbose_name='Dias de afastamento')),
                ('cid', models.CharField(blank=True, max_length=15, verbose_name='CID (opcional)')),
                ('medico', models.CharField(blank=True, max_length=150, verbose_name='Médico (opcional)')),
                ('crm', models.CharField(blank=True, max_length=30, verbose_name='CRM (opcional)')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo/Observações')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='rh/atestados/', verbose_name='Arquivo do Atestado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='rh.funcionariorh')),
            ],
            options={
                'verbose_name': 'Atestado Médico',
                'verbose_name_plural': 'Atestados Médicos',
                'ordering': ['-data_inicio', '-criado_em'],
                'indexes': [models.Index(fields=['funcionario', 'data_inicio'], name='rh_atestado_funcion_f4980f_idx')],
            },
        ),
    ]
