# Generated by Django 5.2.6 on 2025-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.TextField(max_length=30),
        ),
    ]
