# Generated by Django 5.2.5 on 2025-09-17 21:36

import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_cpf_alter_paciente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[pacientes.models.validate_cpf]),
        ),
    ]
