# Generated by Django 5.2.5 on 2025-09-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_extend_paciente_demografico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='endereco',
        ),
    ]
