# Generated by Django 5.2.5 on 2025-09-30 01:01

import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_remove_endereco_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[pacientes.models.validate_cpf]),
        ),
    ]
