# Generated by Django 5.2.6 on 2025-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='destino',
            field=models.CharField(choices=[('Uberaba', 'Uberaba'), ('Fernandopolis', 'Fernandopolis'), ('Sao Jose do Rio Preto', 'Sao Jose do Rio Preto'), ('Barretos', 'Barretos')], max_length=200),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='hora_saida',
            field=models.TimeField(choices=[('duas da manha', '02:00'), ('tres da manha', '03:00')]),
        ),
    ]
