# Generated by Django 5.2.6 on 2025-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_alter_viagem_destino_alter_viagem_hora_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='hora_saida',
            field=models.TimeField(blank=True, choices=[('duas da manha', '02:00'), ('tres da manha', '03:00')], null=True),
        ),
    ]
