# Generated by Django 5.2.5 on 2025-09-04 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_alter_viagem_hora_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='hora_saida',
            field=models.TimeField(blank=True, choices=[(datetime.time(2, 0), '02:00'), (datetime.time(3, 0), '03:00')], null=True),
        ),
    ]
