# Generated by Django 5.2.5 on 2025-09-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0005_viagem_hospital_viagem_motorista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='tipo_transporte',
        ),
        migrations.AddField(
            model_name='viagem',
            name='acompanhante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viagem',
            name='endereco_paciente',
            field=models.CharField(default='Não informado', max_length=150),
        ),
    ]
