# Generated by Django 5.2.5 on 2025-09-27 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0001_initial'),
        ('viagens', '0009_switch_motorista_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='motorista_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_agendadas', to='motorista.motorista'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='acompanhante',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='endereco_paciente',
            field=models.CharField(default='Não informado', max_length=300),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='motorista',
            field=models.CharField(default='Não informado', max_length=150),
        ),
    ]
