# Generated by Django 5.2.5 on 2025-09-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0001_initial'),
        ('viagens', '0010_viagem_motorista_ref_alter_viagem_acompanhante_and_more'),
    ]

    operations = [
        # Em vez de tentar converter CharField -> FK (que falha se houver valores não numéricos),
        # removemos o campo de texto e renomeamos o FK existente 'motorista_ref' para 'motorista'.
        migrations.RemoveField(
            model_name='viagem',
            name='motorista',
        ),
        migrations.RenameField(
            model_name='viagem',
            old_name='motorista_ref',
            new_name='motorista',
        ),
    ]
