# Generated by Django 5.2.5 on 2025-11-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0011_remove_viagem_motorista_ref_alter_viagem_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital de Atendimento',
                'verbose_name_plural': 'Hospitais de Atendimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoAtendimentoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Atendimento',
                'verbose_name_plural': 'Tipos de Atendimento',
                'ordering': ['nome'],
            },
        ),
    ]
