# Generated by Django 5.2.5 on 2025-11-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0012_hospitalatendimento_tipoatendimentoviagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=120)),
                ('uf', models.CharField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cidade de Destino',
                'verbose_name_plural': 'Cidades de Destino',
                'ordering': ['nome_cidade', 'uf'],
                'unique_together': {('nome_cidade', 'uf')},
            },
        ),
    ]
