# Generated by Django 5.2.5 on 2025-09-27 02:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_funcionario_cpf'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('caminhonete', 'Caminhonete'), ('ambulancia', 'Ambulância'), ('van', 'Van'), ('onibus', 'Ônibus'), ('caminhao', 'Caminhão'), ('outro', 'Outro')], default='carro', max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='motorista',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'motorista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='funcionarios.funcionario'),
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('caminhonete', 'Caminhonete'), ('ambulancia', 'Ambulância'), ('van', 'Van'), ('onibus', 'Ônibus'), ('caminhao', 'Caminhão'), ('outro', 'Outro')], max_length=20)),
                ('tipo_combustivel', models.CharField(choices=[('alcool', 'Álcool'), ('gasolina', 'Gasolina'), ('diesel', 'Diesel')], max_length=10)),
                ('local_abastecimento', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('motorista', models.ForeignKey(limit_choices_to={'cargo': 'motorista'}, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='funcionarios.funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='veiculos.veiculo')),
            ],
            options={
                'ordering': ['-data_hora', '-id'],
            },
        ),
    ]
