# Generated by Django 5.2.5 on 2025-09-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_tipo_alter_veiculo_motorista_abastecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('alcool', 'Álcool'), ('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('total_flex', 'Total Flex')], default='gasolina', max_length=12),
        ),
    ]
