# Generated by Django 5.2.5 on 2025-09-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0002_make_cpf_optional'),
        ('veiculos', '0003_veiculo_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='motorista.motorista'),
        ),
    ]
