# Generated by Django 5.2.6 on 2025-11-04
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_veiculo_combustivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=120)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Local de Manutenção',
                'verbose_name_plural': 'Locais de Manutenção',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ManutencaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('revisao', 'Revisão'), ('outro', 'Outro')], default='corretiva', max_length=20)),
                ('data_envio', models.DateField()),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('descricao_problema', models.TextField()),
                ('servicos_realizados', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='veiculos.localmanutencao')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Manutenção de Veículo',
                'verbose_name_plural': 'Manutenções de Veículos',
                'ordering': ['-data_envio', '-id'],
            },
        ),
    ]
