# Generated by Django 5.2.5 on 2025-09-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_alter_abastecimento_motorista'),
        ('veiculos', '0004_alter_abastecimento_motorista_to_motorista'),
    ]

    operations = []
