# Generated by Django 5.2.5 on 2025-11-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_localmanutencao_manutencaoveiculo'),
        ('veiculos', '0006_abastecimento_excluido_em_abastecimento_excluido_por'),
    ]

    operations = [
    ]
