# Generated by Django 5.2.6 on 2025-09-27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria_it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaccess',
            name='can_motorista',
            field=models.BooleanField(default=False, verbose_name='Motoristas'),
        ),
    ]
