# Generated by Django 5.2.5 on 2025-10-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria_it', '0002_add_can_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaccess',
            name='can_rh',
            field=models.BooleanField(default=False, verbose_name='Recursos Humanos'),
        ),
        migrations.AddField(
            model_name='groupaccess',
            name='can_veiculos',
            field=models.BooleanField(default=False, verbose_name='Veículos / Abastecimentos'),
        ),
    ]
