# Generated by Django 5.2.6 on 2025-09-27
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cnh_numero', models.CharField(blank=True, max_length=20)),
                ('cnh_categoria', models.CharField(blank=True, max_length=5)),
                ('cnh_validade', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('escala_trabalho', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['nome_completo']},
        ),
        migrations.CreateModel(
            name='ViagemMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código/ID da viagem')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('origem', models.CharField(max_length=150, verbose_name='Local de origem')),
                ('destino', models.CharField(max_length=150, verbose_name='Local de destino')),
                ('dias_viagem', models.PositiveIntegerField(default=0)),
                ('quantidade_diarias', models.PositiveIntegerField(default=0)),
                ('valor_unitario_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total_diarias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantidade_horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('valor_hora_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total_horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('justificativa_horas_extras', models.TextField(blank=True)),
                ('motivo_viagem', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='motorista.motorista')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo')),
            ],
            options={'ordering': ['-data_inicio', '-id']},
        ),
    ]
