# Generated by Django 5.2.5 on 2025-11-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0002_make_cpf_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
