# Generated by Django 5.2.5 on 2025-09-12 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_alter_paciente_cpf_alter_paciente_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=150, verbose_name='Nome do paciente')),
                ('paciente_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('paciente_cns', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNS')),
                ('paciente_endereco', models.TextField(blank=True, max_length=300, verbose_name='Endereço')),
                ('paciente_telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('data_viagem', models.DateField(verbose_name='Data da viagem')),
                ('numero_diarias', models.PositiveIntegerField(default=1, verbose_name='Número de diárias')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da diária')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(blank=True, help_text='Opcional: vincular a um paciente já cadastrado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'TFD',
                'verbose_name_plural': 'TFD',
                'ordering': ['-data_viagem', '-criado_em'],
            },
        ),
    ]
