# Generated by Django 5.2.5 on 2025-09-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfd',
            name='cidade_destino',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cidade de destino'),
        ),
        migrations.AddField(
            model_name='tfd',
            name='cidade_origem',
            field=models.CharField(default='Iturama', editable=False, max_length=100, verbose_name='Cidade de origem'),
        ),
    ]
