# Generated by Django 5.2.5 on 2025-09-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfd', '0002_tfd_cidade_destino_tfd_cidade_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfd',
            name='autorizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de autorização'),
        ),
        migrations.AddField(
            model_name='tfd',
            name='paciente_assinatura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Assinatura do paciente (texto)'),
        ),
        migrations.AddField(
            model_name='tfd',
            name='secretario_assinatura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Assinatura do secretário (texto)'),
        ),
        migrations.AddField(
            model_name='tfd',
            name='secretario_autorizado',
            field=models.BooleanField(default=False, verbose_name='Autorizado pelo Secretário de Saúde'),
        ),
        migrations.AddField(
            model_name='tfd',
            name='secretario_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do secretário'),
        ),
    ]
