# Generated by Django 5.2.5 on 2025-09-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfd', '0003_tfd_autorizado_em_tfd_paciente_assinatura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tfd',
            options={'ordering': ['-data_inicio', '-criado_em'], 'verbose_name': 'TFD', 'verbose_name_plural': 'TFD'},
        ),
        migrations.RemoveField(
            model_name='tfd',
            name='data_viagem',
        ),
        migrations.AddField(
            model_name='tfd',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data fim'),
        ),
        migrations.AddField(
            model_name='tfd',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data início'),
        ),
    ]
