# Generated by Django 5.2.5 on 2025-09-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfd', '0004_alter_tfd_options_remove_tfd_data_viagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfd',
            name='valor_beneficio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do benefício'),
        ),
    ]
