# Generated by Django 5.2.5 on 2025-09-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfd', '0005_tfd_valor_beneficio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfd',
            name='autorizado_em',
        ),
        migrations.RemoveField(
            model_name='tfd',
            name='paciente_assinatura',
        ),
        migrations.RemoveField(
            model_name='tfd',
            name='secretario_assinatura',
        ),
        migrations.RemoveField(
            model_name='tfd',
            name='secretario_autorizado',
        ),
        migrations.RemoveField(
            model_name='tfd',
            name='secretario_nome',
        ),
    ]
